### ISSUE TITLE
Infer dedent from `where` token after `do` block

### ISSUE THREAD

**Issue by carymrobbins** [Frege/frege#291] opened 2016-07-12 13:54 UTC
The following is valid Haskell, so it'd be nice for it to be supported by Frege. For now (as a workaround), I'm simply dedenting the `where` token by one character.

```frege
foo :: Monad m => m ()
foo = do
  x <- y
  return x
  where
  y = return ()
```

**Comment by mabre** [comment] 2016-07-14 09:05
duplicate of #272
The code can be compiled with version 3.24.100.

**Closed** 2016-07-23 16:32 UTC
